### ISSUE TITLE
Rename - Error( Invalid cross-device link )

### ISSUE THREAD

**Issue by Mazo** [Anthirian/script.filecleaner#38] opened 2015-03-02 11:39 UTC
I currently have filecleaner running on a Rasberry Pi using RaspBMC and pulling videos from a Windows host over SMB. When the script tries to clean it creates the directories in the destination folder but doesn't actually move the files. Log output is here (file paths anonymized):

    11:31:22 T:2732586048  NOTICE: Kodi File Cleaner: Unstacking 'smb://WindowsPC/Video/Show1/TVShow.mkv' is not needed.
    11:31:23 T:2732586048  NOTICE: Previous line repeats 1 times.
    11:31:23 T:2732586048  NOTICE: Kodi File Cleaner: Path exclusion is disabled.
    11:31:23 T:2732586048  NOTICE: Kodi File Cleaner: Attempting to move 'smb://WindowsPC/Video/Show1/TVShow.mkv' to 'smb://WindowsPC/Watched/Show1/TVShow'.
    11:31:23 T:2732586048  NOTICE: Kodi File Cleaner: Moving 'smb://WindowsPC/Video/Show1/TVShow.mkv' to 'smb://WindowsPC/Watched/Show1/TVShow/TVShow.mkv'.
    11:31:23 T:2732586048   ERROR: Rename - Error( Invalid cross-device link )
    11:31:23 T:2732586048   ERROR: Rename - Error renaming file smb://WindowsPC/Video/Show1/TVShow.mkv
    11:31:23 T:2732586048  NOTICE: Kodi File Cleaner: No cleaning required

**Comment by Anthirian** [comment] 2015-03-02 16:02
I think this is caused by using a different network protocol in your addon settings than you use for scraping videos into the library. Could you please post the contents of your addon settings from `special://userdata/addon_data/script.filecleaner/settings.xml` (see [here](http://kodi.wiki/view/Special_protocol) how to find this) so I can take a look? It's also possible you don't have write access to the destination.

**Comment by Mazo** [comment] 2015-03-02 16:21
Both folders have Change & Read access for Everyone. Video sources are also set up using the same SMB paths.

<settings>
    <setting id="clean_movies" value="true" />
    <setting id="clean_music_videos" value="true" />
    <setting id="clean_related" value="true" />
    <setting id="clean_tv_shows" value="true" />
    <setting id="clean_when_idle" value="true" />
    <setting id="clean_when_low_disk_space" value="false" />
    <setting id="clean_when_low_rated" value="false" />
    <setting id="clean_xbmc_library" value="true" />
    <setting id="cleaning_type" value="0" />
    <setting id="create_subdirs" value="true" />
    <setting id="debugging_enabled" value="true" />
    <setting id="default_action" value="0" />
    <setting id="delayed_start" value="10" />
    <setting id="delete_folders" value="true" />
    <setting id="disk_space_check_path" value="special://home" />
    <setting id="disk_space_threshold" value="5.000000" />
    <setting id="enable_expiration" value="false" />
    <setting id="exclusion1" value="" />
    <setting id="exclusion2" value="" />
    <setting id="exclusion3" value="" />
    <setting id="exclusion_enabled" value="false" />
    <setting id="expire_after" value="7" />
    <setting id="holding_folder" value="smb://WindowsPC/Watched/" />
    <setting id="holding_info" value="" />
    <setting id="ignore_extensions" value=".nfo, .nfo-orig, .tbn, .srt, .ass, .srr, .sfv, .nzb, .jpg, .png, .txt" />
    <setting id="ignore_no_rating" value="true" />
    <setting id="minimum_rating" value="6" />
    <setting id="musicvideo_progress_info" value="" />
    <setting id="musicvideo_ratings_info" value="" />
    <setting id="not_in_progress" value="true" />
    <setting id="notifications_enabled" value="true" />
    <setting id="notify_when_idle" value="true" />
    <setting id="reset_exclusions" value="" />
    <setting id="scan_interval" value="30" />
    <setting id="service_enabled" value="true" />
</settings>

**Comment by Anthirian** [comment] 2015-03-02 18:02
Thanks for posting the settings. A few more questions. Have you used this setup successfully with earlier versions of the file cleaner? Have you tried setting the permissions to Full Control instead of Change and Read? Are you certain the permissions are set recursively? Have you mounted the shares within Kodi, within the OS or not at all?

**Comment by Mazo** [comment] 2015-03-02 18:09
No, not had it set up previously due to the compatibility issues with the newer version of Kodi. I did try 4.0.1 and it seemed to run once, but then never again (it moved two video files in total, out of probably a hundred or so watched)

Permissions are applied recursively. Have just tried full control with a restart of RaspBMC after, no change.

Shares are added as libraries through the Videos -> Files menu on the RaspBMC dashboard.

**Comment by Anthirian** [comment] 2015-03-02 18:34
That is quite strange. I'm not sure why this is happening then. I have read there are some issues renaming across file systems or protocols, but not within the same protocol or system. Could you try running the below quick test and report back? I'm curious to see if you can write to the destination at all.

Rename line 620 in `default.py` from
    success.append(bool(xbmcvfs.rename(p, new_path)))
to
    success.append(bool(xbmcvfs.copy(p, new_path)))

This obviously means your videos are going to get copied instead of moved, so it's best to try with a small number of watched videos to avoid a large increase in disk usage.

**Comment by Mazo** [comment] 2015-03-10 17:22
Apologies for the delay in getting back to you. I've just tested it now and yes, that works fine. It's copying the files right now with no errors.

**Comment by Anthirian** [comment] 2015-03-10 17:47
Allright, good to hear that works. I'll be adding some code to make sure to fall back to copy and delete in cases such as yours.

**Comment by scott012** [comment] 2015-03-19 01:08
Has there been a solution for this? I've been experiencing the same issue running XBMC File Cleaner on XBMCBuntu to Ubuntu Server. I've changed the permissions to the files and directories.

Thanks for any help you can give!!!

**Comment by Anthirian** [comment] 2015-03-25 16:14
I just pushed a few commits that should hopefully resolve this issue. During testing I found permission errors occur when either the destination folder is not writable, or the source folder is not writable. The latter I did not expect and may very well be the source of all these problems. 

@Mazo Would you mind checking the source folder permissions for me, just out of curiosity?

@scott012 Could you please test the new code and report back? Remember to backup your library in case something goes wrong.

**Comment by Anthirian** [comment] 2015-06-09 20:19
Closing this issue since the new release featuring this fix is added to the official repository.

**Closed by Anthirian** 2015-06-09 20:19 UTC
